[build]
  command = "pnpm install --no-frozen-lockfile && NODE_OPTIONS='--max-old-space-size=4096' pnpm run build --verbose"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8.10.0"
  NPM_FLAGS = "--version"
  # Añadimos este log de depuración
  DEBUG = "netlify:*"
