[build]
  command = "pnpm install --no-frozen-lockfile && pnpm install postcss-custom-media cssnano --save-dev && NODE_OPTIONS='--max-old-space-size=4096' pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  PNPM_VERSION = "8.10.0"
  NPM_FLAGS = "--version"
  CI = "true"
  NETLIFY_USE_YARN = "false"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
